version: "3.3"

services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $DB_HOST -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    env_file: .env
    volumes:
      - staticfiles:/app/static/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  staticfiles:
  pg_data: